version: 2.1

executors:
  python-35:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/repo
  python-36:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
  python-37:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo

commands:
  build:
    description: "Download and build"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install --no-dev
  test:
    description: "Download and run tests"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install --no-dev
      - run:
          name: Run unit tests
          command: poetry run python -m unittest
  test-with-codecov:
    description: "Download and run tests with code coverage"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Install codecov
          command: poetry run pip install codecov
      - run:
          name: Run unit tests
          command: poetry run coverage run -m unittest
      - run:
          name: Upload coverage to Codecov
          command: poetry run codecov
  lint:
    description: "Lint python files"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Check with black
          command: poetry run black --check gvmtools
      - run:
          name: Run pylint
          command: poetry run pylint --score=n --disable=R gvmtools
      - run:
          name: Check version information
          command: poetry run python -m gvmtools.version verify current
  lint-scripts:
    description: "Lint GVM scripts"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: poetry install
      - run:
          name: Install additional script dependencies
          command: poetry run pip install -r scripts/requirements.txt
      - run:
          name: Check with black
          command: poetry run black --check scripts/*.gmp.py
      - run:
          name: Run pylint
          command: |
            poetry run pylint --rcfile=scripts/.pylintrc --disable=R --ignore=requirements.txt scripts/*

jobs:
  lint-python-files:
    executor: python-36
    steps:
      - lint
  lint-gvm-scripts:
    executor: python-36
    steps:
      - lint-scripts
  build-35:
    executor: python-35
    steps:
      - build
  test-35:
    executor: python-35
    steps:
      - test
  build-36:
    executor: python-36
    steps:
      - build
  test-36:
    executor: python-36
    steps:
      - test
  build-37:
    executor: python-37
    steps:
      - build
  test-37:
    executor: python-37
    steps:
      - test-with-codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint-python-files
      - build-35
      - test-35
      - build-36
      - test-36
      - build-37
      - test-37
